In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
import torch
from torch.testing import make_tensor

from model import InputEmbedding

d_model = 12
vocab_size = 3
batch_size = 3
seq_len = 5
# since this is the tensor for embedding, we need to use int type
t = make_tensor((batch_size,seq_len), device='cpu', dtype=torch.int, low=0, high=vocab_size-1)

input_embedding = InputEmbedding(d_model, vocab_size)
ret = input_embedding(t)
assert ret.shape == (batch_size, seq_len, d_model)
assert ret.dtype == torch.float
assert ret.device.type == "cpu", f"device {ret.device}"
# torch.testing.assert_close(ret, expected, check_layout=True, check_device=True, check_dtype=True)

In [91]:
import torch
from torch.testing import make_tensor

from model import PositionEmbedding

batch_size = 1
d_model = 2
max_seq_len = 5
seq_len = 2
dropout = 0
pe = PositionEmbedding(d_model, max_seq_len, dropout)

t = make_tensor((batch_size, seq_len, d_model), device='cpu', dtype=torch.float32, low=-1, high=1)
ret = pe(t)
expected_diff = torch.tensor([[[0.0000, 1.0000], [0.8415, 0.5403]]], dtype=torch.float32)
torch.testing.assert_close(ret-t, expected_diff, rtol=0.001, atol=0.001)


tensor([[[0.0000, 1.0000],
         [0.8415, 0.5403]]])
tensor([[[ 0.0000e+00,  0.0000e+00],
         [-2.9027e-05,  2.3246e-06]]])


In [121]:
import torch
from torch.testing import make_tensor

from model import LayerNormalization

ln = LayerNormalization()
t = torch.tensor([[1.0, 3.0], [2.0, 4.0]], dtype=torch.float32)
ret = ln(t)
print(t)
print(ret)
print(ln.alpha)
print(ln.beta)

tensor([[ 1.,  3.],
        [-2.,  4.]])
tensor([[-0.7071,  0.7071],
        [-0.7071,  0.7071]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([1.], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)
